### ISSUE TITLE
Review Documentation

### ISSUE THREAD

**Issue by jbear23** [cseseniordesign/rna-nanostructures-2022#10]
User Story:

- As a developer I want to review the previous team's documentation so I can better understand the software.

Acceptance Criteria:

- [x] Summary of previous team's documentation is available for the team

- [x] Team can easily find resources and documentation made by the previous team.

**Comment by PCao2** [comment]
User Story:

- As a developer I want to review the previous team's documentation so I can better understand the software.

Acceptance Criteria:

- [x] Summary of previous team's documentation is available for the team

- [x] Team can easily find resources and documentation made by the previous team.
