### ISSUE TITLE
Research UI Alternatives and current UI implementation

### ISSUE THREAD

**Issue by jbear23** [cseseniordesign/rna-nanostructures-2022#11]
User Story:
- As as developer I want to look into UI alternatives so I can know what frontend to choose to create for the software.

Acceptance Criteria:

- [x] Developers decided on a frontend language to use

- [x] Sponsors have agreed that the frontend language is suitable for the application

**Comment by PCao2** [comment]
User Story:
- As as developer I want to look into UI alternatives so I can know what frontend to choose to create for the software.

Acceptance Criteria:

- [x] Developers decided on a frontend language to use

- [x] Sponsors have agreed that the frontend language is suitable for the application
