### ISSUE TITLE
Request and verify HCC account

### ISSUE THREAD

**Issue by abdualdeen** [cseseniordesign/rna-nanostructures-2022#18]
User Story:

- As a developer I want a HCC account so that I can access the VM for development

Acceptance Criteria:

- [ ] All development team members have an HCC account created and can login

**Comment by PCao2** [comment]
User Story:

- As a developer I want a HCC account so that I can access the VM for development

Acceptance Criteria:

- [ ] All development team members have an HCC account created and can login
