### ISSUE TITLE
Create a new react project for the front-end

### ISSUE THREAD

**Issue by tmcelmury** [cseseniordesign/rna-nanostructures-2022#20]
User Story:
- As a user, I want a demo front end so that I can know what will be attached to the Django backend

Acceptance criteria:

- [x] A working ReactJS Project/Live Server

- [x] A Github Repository that everyone has access to

**Comment by PCao2** [comment]
User Story:
- As a user, I want a demo front end so that I can know what will be attached to the Django backend

Acceptance criteria:

- [ ] A working ReactJS Project/Live Server

- [ ] A Github Repository that everyone has access to
