### ISSUE TITLE
Evaluate issues with Django Airavata backend

### ISSUE THREAD

**Issue by PCao2** [cseseniordesign/rna-nanostructures-2022#28]
User Story:
- As a developer, I want to understand the issues with the backend in order to evaluate how to work with the current backend

Acceptance Criteria:

- [x] Meet with University of Indiana Team

- [x] Verify solution to backend problems works.

- [ ] Ensure all team developers have their environment running

**Comment by ApartmentTzar** [comment]
Documenting bugs is not necessary as Indiana recommended using remote API.  I have confirmed that this works as a solution.
