### ISSUE TITLE
create skeleton for past experiments page

### ISSUE THREAD

**Issue by ApartmentTzar** [cseseniordesign/rna-nanostructures-2022#37]
User Story:
- As a user I want to view all of my past experiments and be able to sort them.  I also want to be able to have an easy way to copy an experiment and make quick modifications and re-submit.

Acceptance Criteria:
- [x] Past list of all experiments submitted by the user are shown sorted by date
- [x] Information about the submitted experiment is shown in the row
- [x] Option to clone any past experiment which will immediately take the user to the submit experiment page with it prepopulated with the same options

**Comment by PCao2** [comment]
removed "List can be sorted by different criteria like status, range of dates etc..." acceptance criteria for Task to be more inline with scope of Release
