### ISSUE TITLE
Separate Software and Front-Facing Webpage

### ISSUE THREAD

**Issue by kgerot** [cseseniordesign/rna-nanostructures-2022#50]
User Story:
As an anonymous user, I want to be able to see an informational page about the application without needing to login or access it to know information about it

Acceptance Criteria:
- [ ] Landing page and Workspace page are seperated by a placeholder Login
- [ ] Landing Page has Contact, About, and Documentation page, as well as login/create account link.
- [ ] Workspace page has "Home", "Portal", and "Design new RNA Scaffold" links/buttons as well as a "Past Experiments"
- [ ] Formatting should be similar to [figma Mockup](https://www.figma.com/file/f3p1ArOyFt2VmIVVUUrZFf/HCC-Senior-Design-Prototype?node-id=0%3A1)
- [ ] Front-facing page (before login page) should be made through Wagtail. If not possible, only focus on  Portal Landing page (after login page) in Vue/React

**Comment by PCao2** [comment]
Deprecated due to structure of front-end application and landing page
