### ISSUE TITLE
Create wireframes/mockups

### ISSUE THREAD

**Issue by jbear23** [cseseniordesign/rna-nanostructures-2022#7]
User Story:
- As a user I want wireframes/mock-ups so that I can get an idea if the interface will be interactive and user friendly.

Acceptance Criteria:

- [x] Wireframes are available for the team to review

- [x] Sponsors have seen and approve the Wireframes

**Comment by PCao2** [comment]
Assigned to Katie Gerot

**Comment by PCao2** [comment]
User Story:
- As a user I want wireframes/mock-ups so that I can get an idea if the interface will be interactive and user friendly.

Acceptance Criteria:

- [x] Wireframes are available for the team to review

- [x] Sponsors have seen and approve the Wireframes
