### ISSUE TITLE
Research API data format

### ISSUE THREAD

**Issue by PCao2** [cseseniordesign/rna-nanostructures-2022#79]
User Story: As a user I want to application to take my job submission and return useful data

Acceptance Criteria:
- [x]  Research what form data should take to be passed to the API Calls
- [x]  Research what form data is returned from the API Calls

**Comment by tmcelmury** [comment]
- most function calls require an authorization token of the type security_model.AuthzToken 
- experiments, compute resources, job submissions, interfaces, and projects are referenced by their id's
- search functions require a gatewayID and username, which are strings
- creating a project/experiment requires a model

https://airavata.apache.org/api-docs/0.16/airavata_api.html#Fn_Airavata_getDetailedExperimentTree

**Comment by tmcelmury** [comment]
- when creating a project, experiment, etc. the function will return its ID as a string
- deleting a project, experiment, validate, etc. returns a boolean indicating the success of the function
-  'get' functions return the object itself or object model
- job status is returned as a string
