### ISSUE TITLE
Research and understand Javascript and ReactJS

### ISSUE THREAD

**Issue by jbear23** [cseseniordesign/rna-nanostructures-2022#8]
User Story:
- As a developer I want to get familiar with the software so that I can visulaize and understand what the sponsors want.

Acceptance Criteria:

- [x]  All developers will have a good understanding of Javascript and ReactJS

- [x]  All developers have finished the ReactJS Tutorial

**Comment by PCao2** [comment]
Should be completed Halfway through R2 Sprint 1

**Comment by PCao2** [comment]
User Story:
- As a developer I want to get familiar with the software so that I can visulaize and understand what the sponsors want.

Acceptance Criteria:

- [ ]  All developers will have a good understanding of Javascript and ReactJS

- [ ]  All developers have finished the ReactJS Tutorial
